const BOARD_END=100;
const STORAGE_KEY='ortopediaGameV10';
const DICE=['⚀','⚁','⚂','⚃','⚄','⚅'];
const CHARACTERS=[
  {name:'La Doctora',role:'Odontóloga',emoji:'👩🏻‍⚕️',reactionEmoji:'😉',color:'#2f8df5',anim:'wink',reaction:'¡Lista para cuidar sonrisas!',desc:'Clínica, decidida y orientada al diagnóstico.'},
  {name:'El Estudiante',role:'Explorador del conocimiento',emoji:'👨🏻‍🎓',reactionEmoji:'🙋🏻‍♂️',color:'#21b56c',anim:'jump',reaction:'¡Vamos a aprender jugando!',desc:'Curioso, observador y siempre listo para aprender.'},
  {name:'Súper Diente',role:'Héroe de la sonrisa',emoji:'🦷',reactionEmoji:'🦷✨',color:'#f34d72',anim:'hero',reaction:'¡Al rescate de las sonrisas!',desc:'Valiente, energético y defensor de las sonrisas.'},
  {name:'Bracki',role:'Maestro de los brackets',emoji:'😁',reactionEmoji:'😜',color:'#8a52e8',anim:'wiggle',reaction:'¡Brackets listos!',desc:'Divertido, ingenioso y especialista en retos.'},
  {name:'La Científica',role:'Investigadora',emoji:'👩🏻‍🔬',reactionEmoji:'💡',color:'#f3b423',anim:'pulse',reaction:'¡Tengo una hipótesis!',desc:'Analítica, creativa y enfocada en la evidencia.'},
  {name:'La Ortodoncista',role:'Especialista en ortodoncia',emoji:'👩🏼‍⚕️🦷',reactionEmoji:'😉✨',color:'#18a7c9',anim:'wink',reaction:'¡A alinear esa sonrisa!',desc:'Experta en oclusión, alineación y planificación ortodóncica.'},
  {name:'La Odontopediatra',role:'Especialista infantil',emoji:'👩🏽‍⚕️🧸',reactionEmoji:'🤗',color:'#ff7aa8',anim:'jump',reaction:'¡Una visita puede ser divertida!',desc:'Amable, paciente y experta en el cuidado dental infantil.'},
  {name:'El Cirujano Maxilofacial',role:'Cirugía oral y maxilofacial',emoji:'👨🏽‍⚕️🩺',reactionEmoji:'👍🏽',color:'#5367d8',anim:'hero',reaction:'¡Plan preciso, manos listas!',desc:'Sereno, preciso y enfocado en los retos quirúrgicos.'},
  {name:'El Endodoncista',role:'Especialista en endodoncia',emoji:'👨🏻‍⚕️🔬',reactionEmoji:'🔍',color:'#00a88f',anim:'pulse',reaction:'¡A encontrar el conducto!',desc:'Minucioso, técnico y especialista en diagnóstico pulpar.'},
  {name:'La Periodoncista',role:'Especialista en encías',emoji:'👩🏾‍⚕️🪥',reactionEmoji:'😁✨',color:'#65b84f',anim:'wiggle',reaction:'¡Encías sanas, sonrisa fuerte!',desc:'Cuida los tejidos de soporte y la salud periodontal.'},
  {name:'La Prostodoncista',role:'Rehabilitación oral',emoji:'👩🏻‍⚕️👑',reactionEmoji:'👑✨',color:'#e29b27',anim:'pulse',reaction:'¡Vamos a reconstruir la sonrisa!',desc:'Creativa y precisa en rehabilitación, coronas y prótesis.'},
  {name:'La Asistente Dental',role:'Asistencia clínica',emoji:'🧑🏼‍⚕️📋',reactionEmoji:'🙌🏼',color:'#e76f51',anim:'jump',reaction:'¡Todo listo para comenzar!',desc:'Organizada, ágil y siempre preparada para apoyar al equipo.'}
];
const RULE_META={
  question:{icon:'❓',title:'Pregunta',message:'Si contestas mal, retrocedes 1 casilla.'},
  case:{icon:'📋',title:'Caso clínico',message:'Excelente +2 · Buena +1 · Incorrecta −1.'},
  back2:{icon:'📁',title:'Perdiste el expediente',message:'Retrocede 2 casillas.'},
  jail:{icon:'⚖️',title:'Cárcel',message:'Tu paciente está muy molesto y te ha demandado. Pierdes 1 turno.'},
  vacation:{icon:'🏖️',title:'Vacaciones',message:'Te fuiste de vacaciones. Regresa al INICIO.'},
  advance1:{icon:'✅',title:'Excelente diagnóstico',message:'Avanza 1 casilla.'},
  advance2:{icon:'🏁',title:'Tratamiento concluido',message:'Avanza 2 casillas.'},
  back1:{icon:'📅',title:'Paciente canceló',message:'Retrocede 1 casilla.'},
  neutral:{icon:'🦷',title:'Casilla'},finish:{icon:'🏆',title:'Meta'}
};
const CELL_TYPES={
  question:new Set([3,8,15,21,28,35,42,49,56,63,70,77,84,91,97]),
  case:new Set([5,12,18,25,32,39,46,53,60,67,74,81,88,95]),
  advance1:new Set([6,23,41,58,76,93]),
  advance2:new Set([11,30,51,72,90]),
  back1:new Set([16,34,55,79,96]),
  back2:new Set([26,65,87]),
  jail:new Set([44,83]),
  vacation:new Set([37,68])
};
const TEACHER_ACTIVE_KEY='ortopediaActiveTeacherQuestionsV1';
const TEACHER_CASE_KEY='ortopediaActiveTeacherCasesV1';
function loadTeacherQuestions(){try{const q=JSON.parse(localStorage.getItem(TEACHER_ACTIVE_KEY)||'[]');return Array.isArray(q)?q.filter(x=>x&&x.text&&Array.isArray(x.options)&&x.options.length>=2):[]}catch{return[]}}
function loadTeacherCases(){try{const c=JSON.parse(localStorage.getItem(TEACHER_CASE_KEY)||'[]');return Array.isArray(c)?c.filter(x=>x&&x.text&&Array.isArray(x.options)&&x.options.length>=2):[]}catch{return[]}}
const questions=[...(window.QUESTIONS||[]),...loadTeacherQuestions()];
const clinicalCases=[...(window.CLINICAL_CASES||[]),...loadTeacherCases()];
let state=null,draft=null,pendingQuestion=null,selectedAnswer=null,pendingAfterDialog=null,soundEnabled=true,timer=null,timerLeft=30;
const $=id=>document.getElementById(id);
const screens=['setup','characters','loadingScreen','game'].map($);
const board=$('board'),playerCount=$('playerCount'),playerNames=$('playerNames'),resumeBtn=$('resumeBtn'),rollBtn=$('rollBtn'),statusText=$('statusText');
const questionDialog=$('questionDialog'),eventDialog=$('eventDialog'),rulesDialog=$('rulesDialog');
function showScreen(el){screens.forEach(x=>x?.classList.remove('active'));el.classList.add('active')}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function ruleForCell(n){if(n===0)return{type:'start'};if(n>=100)return{type:'finish'};for(const [type,set] of Object.entries(CELL_TYPES))if(set.has(n)){if(type==='question')return{type,deck:(n%3)+1};if(type==='case')return{type,deck:(n%5)+1};return{type}}return{type:'neutral'}}
function buildNameInputs(){playerNames.innerHTML='';const count=Number(playerCount.value);for(let i=0;i<count;i++){const row=document.createElement('label');row.className='name-row';row.innerHTML=`<span class="player-number">${i+1}</span><input id="name-${i}" maxlength="20" value="Jugador ${i+1}" aria-label="Nombre del jugador ${i+1}">`;playerNames.appendChild(row)}}
function beginCharacterSelection(){const count=Number(playerCount.value);draft={count,names:Array.from({length:count},(_,i)=>($(`name-${i}`).value||`Jugador ${i+1}`).trim()),characters:Array(count).fill(null),pickerIndex:0};showScreen($('characters'));renderPicker();tone('select')}
function renderPicker(){const i=draft.pickerIndex,taken=new Set(draft.characters.filter((x,j)=>x!==null&&j!==i));$('pickerTitle').textContent=`${draft.names[i]}, elige tu personaje`;$('pickerHint').textContent=`Jugador ${i+1} de ${draft.count}. Cada personaje solo puede elegirse una vez.`;const grid=$('characterGrid');grid.innerHTML='';CHARACTERS.forEach((ch,idx)=>{const b=document.createElement('button');b.type='button';b.disabled=taken.has(idx);b.className=`character-card${draft.characters[i]===idx?' selected':''}${taken.has(idx)?' taken':''}`;b.dataset.char=idx;b.style.setProperty('--accent',ch.color);b.innerHTML=`<div class="character-art">${ch.emoji}</div><span class="character-bubble" hidden>${ch.reaction}</span><span class="pawn" style="--pawn:${ch.color}"></span><h3>${ch.name}</h3><b>${ch.role}</b><p>${ch.desc}</p><span class="select-label">${taken.has(idx)?'En uso':draft.characters[i]===idx?'Seleccionado':'Seleccionar'}</span>`;b.onclick=()=>{draft.characters[i]=idx;tone('select');renderPicker();requestAnimationFrame(()=>reactCharacter(idx))};grid.appendChild(b)});$('pickerNextBtn').disabled=draft.characters[i]===null;$('pickerNextBtn').textContent=i===draft.count-1?'Comenzar partida →':'Siguiente →';$('pickedSummary').innerHTML=draft.names.map((n,j)=>`<span>${esc(n)} · ${draft.characters[j]===null?'sin elegir':CHARACTERS[draft.characters[j]].name}</span>`).join('')}
function reactCharacter(idx){const ch=CHARACTERS[idx],card=document.querySelector(`[data-char="${idx}"]`);if(!card||!ch)return;const art=card.querySelector('.character-art'),bubble=card.querySelector('.character-bubble');if(!art)return;art.textContent=ch.reactionEmoji||ch.emoji;art.classList.remove('reaction-wink','reaction-jump','reaction-hero','reaction-wiggle','reaction-pulse');void art.offsetWidth;art.classList.add('reaction-'+ch.anim);if(bubble)bubble.hidden=false;setTimeout(()=>{if(document.body.contains(art)){art.textContent=ch.emoji;art.classList.remove('reaction-'+ch.anim)}if(bubble&&document.body.contains(bubble))bubble.hidden=true},780)}
function pickerNext(){if(draft.characters[draft.pickerIndex]===null)return;if(draft.pickerIndex<draft.count-1){draft.pickerIndex++;renderPicker()}else startWithLoading()}
function pickerBack(){if(draft.pickerIndex>0){draft.pickerIndex--;renderPicker()}else showScreen($('setup'))}
async function startWithLoading(){showScreen($('loadingScreen'));tone('start');await delay(700);state={version:10,players:Array.from({length:draft.count},(_,i)=>({name:draft.names[i],position:0,skipTurns:0,character:draft.characters[i],color:CHARACTERS[draft.characters[i]].color})),current:0,usedQuestionIds:[],usedCaseIds:[],turn:1,locked:false};saveGame();showScreen($('game'));buildBoard();render();statusText.textContent=`${state.players[0].name}, tira los dos dados.`}
function buildBoard(){board.querySelectorAll('.cell,.start-marker').forEach(n=>n.remove());const start=document.createElement('div');start.className='start-marker';start.innerHTML='<b>INICIO</b><span>🚩</span>';board.appendChild(start);for(let n=1;n<=100;n++){const t=(n-1)/99;const turns=5.15;const theta=-Math.PI*.72+t*turns*2*Math.PI;const rx=45-35.2*t,ry=43-33.2*t;const x=50+rx*Math.cos(theta),y=50+ry*Math.sin(theta);const r=ruleForCell(n),m=RULE_META[r.type]||RULE_META.neutral;const c=document.createElement('div');c.className=`cell ${r.type}${n===100?' finish':''}`;c.dataset.cell=n;c.style.left=`${x}%`;c.style.top=`${y}%`;c.style.zIndex=100-n;c.innerHTML=`<span class="cell-number">${n}</span>${r.type!=='neutral'&&r.type!=='finish'?`<span class="cell-icon">${m.icon}</span>`:''}<span class="tokens"></span>`;board.appendChild(c)}}
function render(){if(!state)return;document.querySelectorAll('.tokens').forEach(x=>x.innerHTML='');state.players.forEach((p,i)=>{if(p.position<=0)return;const host=document.querySelector(`[data-cell="${Math.min(p.position,100)}"] .tokens`);if(host){const tok=document.createElement('span');tok.className='board-token';tok.style.setProperty('--token',p.color);tok.textContent=CHARACTERS[p.character]?.emoji||'●';tok.title=p.name;host.appendChild(tok)}});$('scoreList').innerHTML=state.players.map((p,i)=>{const ch=CHARACTERS[p.character]||CHARACTERS[0];return `<div class="player-row ${i===state.current?'current':''}" style="--player:${p.color}"><div class="avatar">${ch.emoji}</div><div><b>${esc(p.name)}</b><small>${ch.name} · ${p.position===0?'Inicio':p.position>=100?'Meta':`Casilla ${p.position}`}${p.skipTurns?` · pierde ${p.skipTurns} turno`:''}</small><div class="progress"><i style="width:${Math.min(100,p.position)}%"></i></div></div><strong>${Math.min(p.position,100)}/100</strong></div>`}).join('');$('turnLabel').textContent=state.players[state.current]?.name||'Jugador';rollBtn.disabled=state.locked;saveGame()}
async function rollDice(){if(!state||state.locked)return;state.locked=true;rollBtn.disabled=true;const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);for(let i=0;i<8;i++){$('dice1').textContent=DICE[Math.floor(Math.random()*6)];$('dice2').textContent=DICE[Math.floor(Math.random()*6)];$('dice1').classList.add('rolling');$('dice2').classList.add('rolling');await delay(55)}$('dice1').textContent=DICE[a-1];$('dice2').textContent=DICE[b-1];$('dice1').classList.remove('rolling');$('dice2').classList.remove('rolling');$('diceTotal').textContent=a+b;tone('dice');statusText.textContent=`${state.players[state.current].name} obtuvo ${a} + ${b} = ${a+b}.`;await move(a+b);if(state.players[state.current].position>=100)return showWinner(state.players[state.current]);setTimeout(()=>triggerCell(state.players[state.current].position),180)}
async function move(delta){const p=state.players[state.current],target=Math.max(0,Math.min(100,p.position+delta)),step=target>=p.position?1:-1;while(p.position!==target){p.position+=step;render();await delay(85)}}
function triggerCell(cell){const r=ruleForCell(cell);if(r.type==='question')return startQuestion(r.deck);if(r.type==='case')return startCase(r.deck);if(r.type==='advance1')return movement('advance1',1);if(r.type==='advance2')return movement('advance2',2);if(r.type==='back1')return movement('back1',-1);if(r.type==='back2')return movement('back2',-2);if(r.type==='vacation')return vacation();if(r.type==='jail')return jail();if(r.type==='finish')return showWinner(state.players[state.current]);statusText.textContent='Casilla de descanso. Siguiente turno.';setTimeout(endTurn,450)}
function pickUnused(pool,key){if(!pool.length)return null;let available=pool.filter(x=>!state[key].includes(String(x.id)));if(!available.length){const ids=new Set(pool.map(x=>String(x.id)));state[key]=state[key].filter(id=>!ids.has(id));available=pool}const item=available[Math.floor(Math.random()*available.length)];state[key].push(String(item.id));return item}
function startQuestion(deck){const q=pickUnused(questions.filter(x=>x.deck===deck),'usedQuestionIds');if(!q)return endTurn();pendingQuestion={...q,kind:'question'};selectedAnswer=null;showQuestion()}
function startCase(deck){const q=pickUnused(clinicalCases.filter(x=>x.deck===deck),'usedCaseIds');if(!q)return endTurn();pendingQuestion={...q,kind:'case'};selectedAnswer=null;showQuestion()}
function showQuestion(){stopTimer();const q=pendingQuestion;$('questionCategory').textContent=q.kind==='case'?`📋 Caso clínico · Sobre ${q.deck}${q.origin==='teacher'?' · Docente':''}`:`❓ Pregunta · Sobre ${q.deck}${q.origin==='teacher'?' · Docente':''}`;$('questionNumber').textContent=q.kind==='case'?q.id:`Pregunta ${q.id}`;$('questionText').textContent=q.text;$('feedback').hidden=true;$('confirmAnswerBtn').hidden=false;$('confirmAnswerBtn').disabled=true;$('continueBtn').hidden=true;$('timerDisplay').textContent='30';$('timerBtn').disabled=false;$('timerBtn').textContent='Iniciar 30 s';const media=$('questionMedia');media.hidden=true;media.innerHTML='';if(q.mediaPending){media.hidden=false;media.innerHTML='<p>🎵🎬 Esta pregunta utiliza contenido multimedia en la versión original. La mecánica de respuesta permanece disponible.</p>'}const host=$('questionOptions');host.innerHTML='';q.options.forEach((opt,i)=>{const b=document.createElement('button');b.type='button';b.className='option';b.innerHTML=`<span>${String.fromCharCode(65+i)}</span><b>${esc(opt)}</b>`;b.onclick=()=>{selectedAnswer=i;document.querySelectorAll('.option').forEach((e,j)=>e.classList.toggle('selected',i===j));$('confirmAnswerBtn').disabled=false};host.appendChild(b)});questionDialog.showModal()}
function confirmAnswer(){if(selectedAnswer===null||!pendingQuestion)return;stopTimer();const opts=[...document.querySelectorAll('.option')];opts.forEach(o=>{o.disabled=true;o.classList.remove('selected')});let delta=0,heading='',detail='',snd='error';if(pendingQuestion.kind==='question'){const ok=selectedAnswer===pendingQuestion.correct;opts[pendingQuestion.correct]?.classList.add('correct');if(ok){heading='Correcta · permaneces en tu casilla';snd='correct'}else{opts[selectedAnswer]?.classList.add('wrong');delta=-1;heading='Incorrecta · retrocedes 1 casilla'}detail=pendingQuestion.explanation||'Continúa el recorrido.'}else{const grade=pendingQuestion.grades?.[selectedAnswer]||'incorrect';opts[selectedAnswer]?.classList.add(grade==='incorrect'?'wrong':'correct');if(grade==='excellent'){delta=2;heading='Excelente · avanzas 2 casillas';snd='excellent'}else if(grade==='good'){delta=1;heading='Buena · avanzas 1 casilla';snd='correct'}else{delta=-1;heading='Incorrecta · retrocedes 1 casilla'}detail=pendingQuestion.feedback?.[selectedAnswer]||'Revisa el razonamiento clínico.'}tone(snd);pendingQuestion.resultDelta=delta;$('feedback').hidden=false;$('feedback').innerHTML=`<strong>${esc(heading)}</strong><span>${esc(detail)}</span>`;$('confirmAnswerBtn').hidden=true;$('continueBtn').hidden=false}
async function continueAfterQuestion(){stopTimer();const d=pendingQuestion?.resultDelta||0;pendingQuestion=null;questionDialog.close();if(d)await move(d);if(state.players[state.current].position>=100)return showWinner(state.players[state.current]);endTurn()}
function startTimer(){if(timer)return;timerLeft=30;$('timerBtn').disabled=true;timer=setInterval(()=>{timerLeft--;$('timerDisplay').textContent=Math.max(0,timerLeft);if(timerLeft<=0){stopTimer();tone('alarm');$('timerBtn').textContent='Tiempo terminado'}},1000)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function movement(type,delta){const m=RULE_META[type];showEvent(m.title,m.message,m.icon,async()=>{await move(delta);if(state.players[state.current].position>=100)return showWinner(state.players[state.current]);endTurn()})}
function vacation(){const m=RULE_META.vacation;showEvent(m.title,m.message,m.icon,async()=>{state.players[state.current].position=0;render();await delay(350);endTurn()})}
function jail(){const m=RULE_META.jail;state.players[state.current].skipTurns=(state.players[state.current].skipTurns||0)+1;render();showEvent(m.title,m.message,m.icon,endTurn)}
function showEvent(title,text,icon,cb){$('eventIcon').textContent=icon;$('eventTitle').textContent=title;$('eventText').textContent=text;pendingAfterDialog=cb;eventDialog.showModal()}
function closeEvent(){eventDialog.close();const cb=pendingAfterDialog;pendingAfterDialog=null;cb?.()}
function endTurn(){state.current=(state.current+1)%state.players.length;state.turn++;let guard=0;const skipped=[];while(state.players[state.current].skipTurns>0&&guard<state.players.length*2){const p=state.players[state.current];p.skipTurns--;skipped.push(`${p.name} pierde este turno por Cárcel.`);state.current=(state.current+1)%state.players.length;state.turn++;guard++}state.locked=false;render();statusText.textContent=(skipped.length?skipped.join(' ')+' ':'')+`${state.players[state.current].name}, tira los dos dados.`}
function showWinner(p){state.locked=true;p.position=100;render();$('winnerTitle').textContent='¡Llegaste a la META!';$('winnerText').textContent=`${p.name} completó las 100 casillas de El camino de la ortopedia dental.`;$('winnerDialog').showModal();tone('win')}
function tone(kind='neutral'){if(!soundEnabled)return;try{const AC=window.AudioContext||window.webkitAudioContext,ctx=new AC(),o=ctx.createOscillator(),g=ctx.createGain();const f={error:180,correct:640,excellent:850,alarm:240,dice:420,select:560,start:700,win:920}[kind]||500;o.frequency.value=f;g.gain.value=.04;o.connect(g).connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.17);o.stop(ctx.currentTime+.18)}catch{}}
function saveGame(){if(state)localStorage.setItem(STORAGE_KEY,JSON.stringify(state));resumeBtn.hidden=!localStorage.getItem(STORAGE_KEY)}
function migrate(){if(localStorage.getItem(STORAGE_KEY))return;const old=localStorage.getItem('ortopediaGameV05');if(!old)return;try{const s=JSON.parse(old);if(!s.players?.length)return;s.version=10;s.players=s.players.slice(0,5);s.players.forEach((p,i)=>{p.position=Math.min(99,Math.round((p.position||0)/38*100));p.character=Math.min(CHARACTERS.length-1,typeof p.character==='number'?p.character:i%CHARACTERS.length);p.color=CHARACTERS[p.character].color;p.skipTurns=p.skipTurns||0});s.usedQuestionIds=s.usedQuestionIds||[];s.usedCaseIds=s.usedCaseIds||[];s.current=Math.min(s.current||0,s.players.length-1);s.locked=false;localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
function loadGame(){try{state=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!state?.players?.length)return;state.players=state.players.slice(0,5);state.players.forEach((p,i)=>{p.character=Math.min(CHARACTERS.length-1,typeof p.character==='number'?p.character:i%CHARACTERS.length);p.color=CHARACTERS[p.character].color;p.skipTurns=p.skipTurns||0});state.usedQuestionIds=state.usedQuestionIds||[];state.usedCaseIds=state.usedCaseIds||[];state.locked=false;showScreen($('game'));buildBoard();render();statusText.textContent=`Partida recuperada. ${state.players[state.current].name}, tira los dos dados.`}catch{localStorage.removeItem(STORAGE_KEY)}}
function resetGame(){if(!confirm('¿Reiniciar la partida?'))return;localStorage.removeItem(STORAGE_KEY);state=null;showScreen($('setup'));buildNameInputs()}
function playAgain(){$('winnerDialog').close();localStorage.removeItem(STORAGE_KEY);state=null;showScreen($('setup'));buildNameInputs()}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
playerCount.onchange=buildNameInputs;$('chooseCharactersBtn').onclick=beginCharacterSelection;$('pickerNextBtn').onclick=pickerNext;$('pickerBackBtn').onclick=pickerBack;resumeBtn.onclick=loadGame;rollBtn.onclick=rollDice;$('confirmAnswerBtn').onclick=confirmAnswer;$('continueBtn').onclick=continueAfterQuestion;$('eventContinueBtn').onclick=closeEvent;$('timerBtn').onclick=startTimer;$('resetBtn').onclick=resetGame;$('playAgainBtn').onclick=playAgain;$('soundBtn').onclick=()=>{soundEnabled=!soundEnabled;$('soundBtn').textContent=soundEnabled?'🔊':'🔇'};$('rulesBtn').onclick=()=>rulesDialog.showModal();$('closeRulesBtn').onclick=()=>rulesDialog.close();
migrate();buildNameInputs();buildBoard();resumeBtn.hidden=!localStorage.getItem(STORAGE_KEY);if('serviceWorker'in navigator&&location.protocol==='https:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
