const STORAGE_KEY='ortopediaTeacherActivitiesV1';
const ACTIVE_KEY='ortopediaActiveTeacherQuestionsV1';
let activities=[],selectedId=null,editingQuestionId=null,runState=null;
const $=id=>document.getElementById(id);
function uid(prefix='id'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function load(){try{activities=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(!Array.isArray(activities))activities=[]}catch{activities=[]}selectedId=activities[0]?.id||null;render()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(activities));syncActiveQuestions();renderStats()}
function syncActiveQuestions(){const out=[];for(const a of activities.filter(x=>x.enabled)){for(const q of a.questions||[]){out.push({id:'teacher-'+q.id,deck:Number(q.deck)||1,origin:'teacher',activityId:a.id,activityTitle:a.title,text:q.text,options:q.options,correct:q.correct,explanation:q.explanation||''})}}localStorage.setItem(ACTIVE_KEY,JSON.stringify(out))}
function render(){renderStats();renderActivities();renderEditor()}
function renderStats(){const qs=activities.flatMap(a=>a.questions||[]);$('activityCount').textContent=activities.length;$('questionCount').textContent=qs.length;$('activeCount').textContent=activities.filter(a=>a.enabled).reduce((n,a)=>n+(a.questions?.length||0),0)}
function renderActivities(){const host=$('activityList');host.innerHTML='';if(!activities.length){host.innerHTML='<p class="hint">Todavía no hay actividades.</p>';return}activities.forEach(a=>{const b=document.createElement('div');b.className='activity-item'+(a.id===selectedId?' active':'');b.innerHTML='<b>'+esc(a.title||'Actividad sin título')+'</b><small>'+(a.questions?.length||0)+' preguntas · '+(a.enabled?'Activa en tablero':'Solo actividad')+'</small>';b.onclick=()=>{selectedId=a.id;editingQuestionId=null;render()};host.appendChild(b)})}
function current(){return activities.find(a=>a.id===selectedId)||null}
function renderEditor(){const a=current();$('emptyState').hidden=!!a;$('editorState').hidden=!a;if(!a)return;$('activityTitle').value=a.title||'';$('activityInstructions').value=a.instructions||'';$('activityEnabled').checked=!!a.enabled;$('questionNumberBadge').textContent=(a.questions?.length||0)+' preguntas';renderQuestionList(a)}
function newActivity(){const a={id:uid('act'),title:'Nueva actividad',instructions:'',enabled:false,questions:[]};activities.unshift(a);selectedId=a.id;editingQuestionId=null;save();render();setTimeout(()=>$('activityTitle').select(),0)}
function updateActivity(){const a=current();if(!a)return;a.title=$('activityTitle').value.trim()||'Actividad sin título';a.instructions=$('activityInstructions').value.trim();a.enabled=$('activityEnabled').checked;save();renderActivities()}
function deleteActivity(){const a=current();if(!a)return;if(!confirm('¿Eliminar esta actividad y todas sus preguntas?'))return;activities=activities.filter(x=>x.id!==a.id);selectedId=activities[0]?.id||null;editingQuestionId=null;save();render()}
function readQuestionForm(){const text=$('questionTextInput').value.trim();const opts=[...document.querySelectorAll('.option-input')].map(x=>x.value.trim());while(opts.length&& !opts[opts.length-1])opts.pop();if(!text)return alert('Escribe la pregunta.'),null;if(opts.length<2||opts.some(x=>!x))return alert('Completa al menos dos opciones consecutivas.'),null;const correct=Number($('correctOption').value);if(correct>=opts.length)return alert('La respuesta correcta debe corresponder a una opción escrita.'),null;return{id:editingQuestionId||uid('q'),text,options:opts,correct,deck:Number($('questionDeck').value)||1,explanation:$('questionExplanation').value.trim()}}
function saveQuestion(){const a=current(),q=readQuestionForm();if(!a||!q)return;if(editingQuestionId){const i=a.questions.findIndex(x=>x.id===editingQuestionId);if(i>=0)a.questions[i]=q}else a.questions.push(q);save();clearQuestionForm();renderQuestionList(a)}
function clearQuestionForm(){editingQuestionId=null;$('questionTextInput').value='';document.querySelectorAll('.option-input').forEach(x=>x.value='');$('correctOption').value='0';$('questionDeck').value='1';$('questionExplanation').value='';$('saveQuestionBtn').textContent='Agregar pregunta';$('cancelEditBtn').hidden=true;$('questionEditorTitle').textContent='Agregar pregunta'}
function editQuestion(id){const a=current(),q=a?.questions.find(x=>x.id===id);if(!q)return;editingQuestionId=id;$('questionTextInput').value=q.text;q.options.forEach((v,i)=>{const el=document.querySelector('[data-option="'+i+'"]');if(el)el.value=v});for(let i=q.options.length;i<4;i++){const el=document.querySelector('[data-option="'+i+'"]');if(el)el.value=''}$('correctOption').value=String(q.correct);$('questionDeck').value=String(q.deck||1);$('questionExplanation').value=q.explanation||'';$('saveQuestionBtn').textContent='Guardar cambios';$('cancelEditBtn').hidden=false;$('questionEditorTitle').textContent='Editar pregunta';$('questionTextInput').focus()}
function deleteQuestion(id){const a=current();if(!a)return;if(!confirm('¿Eliminar esta pregunta?'))return;a.questions=a.questions.filter(x=>x.id!==id);save();if(editingQuestionId===id)clearQuestionForm();renderQuestionList(a)}
function renderQuestionList(a){const host=$('questionList');host.innerHTML='';(a.questions||[]).forEach((q,i)=>{const d=document.createElement('article');d.className='question-item';d.innerHTML='<header><h3>'+(i+1)+'. '+esc(q.text)+'</h3><span class="pill">Sobre '+(q.deck||1)+'</span></header><ol type="A">'+q.options.map((o,j)=>'<li class="'+(j===q.correct?'correct':'')+'">'+esc(o)+(j===q.correct?' ✓':'')+'</li>').join('')+'</ol>'+(q.explanation?'<p class="hint"><b>Retroalimentación:</b> '+esc(q.explanation)+'</p>':'')+'<footer><button class="small-btn edit">Editar</button><button class="small-btn delete">Eliminar</button></footer>';d.querySelector('.edit').onclick=()=>editQuestion(q.id);d.querySelector('.delete').onclick=()=>deleteQuestion(q.id);host.appendChild(d)});if(!(a.questions||[]).length)host.innerHTML='<p class="hint">Añade la primera pregunta de esta actividad.</p>'}
function exportData(){if(!activities.length)return alert('No hay actividades para exportar.');const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),activities},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='actividades-ortopedia-dental.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(file){try{const data=JSON.parse(await file.text());const incoming=Array.isArray(data)?data:data.activities;if(!Array.isArray(incoming))throw new Error();const clean=incoming.map(a=>({id:uid('act'),title:String(a.title||'Actividad importada').slice(0,80),instructions:String(a.instructions||'').slice(0,300),enabled:false,questions:Array.isArray(a.questions)?a.questions.map(q=>({id:uid('q'),text:String(q.text||'').slice(0,500),options:(q.options||[]).map(x=>String(x).slice(0,220)).slice(0,4),correct:Number(q.correct)||0,deck:[1,2,3].includes(Number(q.deck))?Number(q.deck):1,explanation:String(q.explanation||'').slice(0,500)})).filter(q=>q.text&&q.options.length>=2):[]}));activities=[...clean,...activities];selectedId=clean[0]?.id||selectedId;save();render();alert('Actividades importadas correctamente.')}catch{alert('No se pudo importar el archivo. Verifica que sea un JSON exportado desde el Modo Docente.')}finally{$('importInput').value=''}}
function openRun(){const a=current();if(!a||!a.questions?.length)return alert('Agrega al menos una pregunta antes de iniciar.');$('runTitle').textContent=a.title;$('runInstructions').textContent=a.instructions||'Responde las preguntas y revisa tu resultado al final.';$('runIntro').hidden=false;$('runQuestion').hidden=true;$('runResult').hidden=true;$('runDialog').showModal()}
function startRun(){const a=current();let qs=a.questions.map(q=>({...q}));if($('shuffleQuestions').checked)qs.sort(()=>Math.random()-.5);runState={questions:qs,index:0,score:0,answered:false,student:$('studentName').value.trim()||'Estudiante'};$('runIntro').hidden=true;$('runQuestion').hidden=false;showRunQuestion()}
function showRunQuestion(){const s=runState,q=s.questions[s.index];$('runCounter').textContent='Pregunta '+(s.index+1)+' de '+s.questions.length;$('runScore').textContent='Aciertos: '+s.score;$('runQuestionText').textContent=q.text;$('runFeedback').hidden=true;$('nextRunBtn').hidden=true;s.answered=false;const host=$('runOptions');host.innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='run-option';b.textContent=String.fromCharCode(65+i)+'. '+o;b.onclick=()=>answerRun(i,b);host.appendChild(b)})}
function answerRun(i,btn){if(runState.answered)return;runState.answered=true;const q=runState.questions[runState.index];const all=[...document.querySelectorAll('.run-option')];all.forEach((b,j)=>{b.disabled=true;if(j===q.correct)b.classList.add('correct')});if(i===q.correct)runState.score++;else btn.classList.add('wrong');$('runFeedback').hidden=false;$('runFeedback').innerHTML='<b>'+(i===q.correct?'✅ Correcta':'❌ Incorrecta')+'</b><br>'+esc(q.explanation||('Respuesta correcta: '+q.options[q.correct]));$('runScore').textContent='Aciertos: '+runState.score;$('nextRunBtn').hidden=false}
function nextRun(){runState.index++;if(runState.index>=runState.questions.length)return finishRun();showRunQuestion()}
function finishRun(){$('runQuestion').hidden=true;$('runResult').hidden=false;const total=runState.questions.length,pct=Math.round(runState.score/total*100);$('resultText').textContent=runState.student+': '+runState.score+' de '+total+' respuestas correctas ('+pct+'%).'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('newActivityBtn').onclick=newActivity;$('emptyNewBtn').onclick=newActivity;$('activityTitle').oninput=updateActivity;$('activityInstructions').oninput=updateActivity;$('activityEnabled').onchange=updateActivity;$('deleteActivityBtn').onclick=deleteActivity;$('saveQuestionBtn').onclick=saveQuestion;$('cancelEditBtn').onclick=clearQuestionForm;$('exportBtn').onclick=exportData;$('importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('runActivityBtn').onclick=openRun;$('closeRunBtn').onclick=()=>$('runDialog').close();$('startRunBtn').onclick=startRun;$('nextRunBtn').onclick=nextRun;$('restartRunBtn').onclick=()=>{$('runResult').hidden=true;$('runIntro').hidden=false};
load();
